#!/usr/bin/env python
###################################
# USage:
#  portscan
#  Input target host name or address: localhost
#  Input target port: 80
#  Port 80 open!
###################################
import socket

target_host = input('Input target host name or address: ')
port        = input('Input target port: ')

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(1)
return_code = sock.connect_ex((target_host, int(port)))
sock.close()

if return_code == 0:
    print("Port %s open!" % (port))
else:
    print("Port %s closed!" % (port))
